// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/messages.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Llaves struct {
	Numero               string   `protobuf:"bytes,1,opt,name=numero,proto3" json:"numero,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Llaves) Reset()         { *m = Llaves{} }
func (m *Llaves) String() string { return proto.CompactTextString(m) }
func (*Llaves) ProtoMessage()    {}
func (*Llaves) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c20020f3e65b37d, []int{0}
}

func (m *Llaves) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Llaves.Unmarshal(m, b)
}
func (m *Llaves) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Llaves.Marshal(b, m, deterministic)
}
func (m *Llaves) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Llaves.Merge(m, src)
}
func (m *Llaves) XXX_Size() int {
	return xxx_messageInfo_Llaves.Size(m)
}
func (m *Llaves) XXX_DiscardUnknown() {
	xxx_messageInfo_Llaves.DiscardUnknown(m)
}

var xxx_messageInfo_Llaves proto.InternalMessageInfo

func (m *Llaves) GetNumero() string {
	if m != nil {
		return m.Numero
	}
	return ""
}

type Confirmar struct {
	Flag                 string   `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Confirmar) Reset()         { *m = Confirmar{} }
func (m *Confirmar) String() string { return proto.CompactTextString(m) }
func (*Confirmar) ProtoMessage()    {}
func (*Confirmar) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c20020f3e65b37d, []int{1}
}

func (m *Confirmar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Confirmar.Unmarshal(m, b)
}
func (m *Confirmar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Confirmar.Marshal(b, m, deterministic)
}
func (m *Confirmar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Confirmar.Merge(m, src)
}
func (m *Confirmar) XXX_Size() int {
	return xxx_messageInfo_Confirmar.Size(m)
}
func (m *Confirmar) XXX_DiscardUnknown() {
	xxx_messageInfo_Confirmar.DiscardUnknown(m)
}

var xxx_messageInfo_Confirmar proto.InternalMessageInfo

func (m *Confirmar) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

func init() {
	proto.RegisterType((*Llaves)(nil), "Llaves")
	proto.RegisterType((*Confirmar)(nil), "Confirmar")
}

func init() { proto.RegisterFile("protos/messages.proto", fileDescriptor_8c20020f3e65b37d) }

var fileDescriptor_8c20020f3e65b37d = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x2d, 0xd6, 0x03, 0xf3, 0x95, 0x14,
	0xb8, 0xd8, 0x7c, 0x72, 0x12, 0xcb, 0x52, 0x8b, 0x85, 0xc4, 0xb8, 0xd8, 0xf2, 0x4a, 0x73, 0x53,
	0x8b, 0xf2, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xa0, 0x3c, 0x25, 0x79, 0x2e, 0x4e, 0xe7,
	0xfc, 0xbc, 0xb4, 0xcc, 0xa2, 0xdc, 0xc4, 0x22, 0x21, 0x21, 0x2e, 0x96, 0xb4, 0x9c, 0xc4, 0x74,
	0xa8, 0x12, 0x30, 0xdb, 0x28, 0x99, 0x8b, 0x2f, 0x38, 0xb5, 0xa8, 0x2c, 0xb5, 0xa8, 0x18, 0x44,
	0x65, 0x26, 0xa7, 0x0a, 0xa9, 0x72, 0xf1, 0xf8, 0x26, 0xe6, 0xa5, 0x24, 0x16, 0x41, 0x8d, 0x66,
	0xd7, 0x83, 0x30, 0xa4, 0xb8, 0xf4, 0xe0, 0x46, 0x29, 0x31, 0x08, 0x69, 0x71, 0x09, 0x42, 0x94,
	0xf9, 0xe5, 0x3b, 0x26, 0x27, 0xa7, 0xa6, 0x64, 0xa6, 0xe4, 0xe3, 0x52, 0xeb, 0x24, 0x18, 0xc5,
	0x8f, 0xe6, 0x81, 0x24, 0x36, 0xb0, 0x80, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x36, 0x94, 0x21,
	0xce, 0xda, 0x00, 0x00, 0x00,
}
