FROM golang:1.21

WORKDIR /europa
COPY europa.go .
RUN go mod init containerized-go-app
RUN go mod tidy

COPY parametros_de_inicio.txt .

RUN go get
RUN go build -o /docker-europa

EXPOSE 8080

CMD ["/docker-europa"]