FROM golang:1.21

WORKDIR /asia
COPY asia.go .
RUN go mod init containerized-go-app
RUN go mod tidy

COPY parametros_de_inicio.txt .

RUN go get
RUN go build -o /docker-asia

EXPOSE 8080

CMD ["/docker-asia"]